version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16 # Version de Node.js à utiliser
    steps:
      - checkout # Récupère le code source
      - run:
          name: Installer les dépendances
          command: npm install
  docker-build:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Construire l'image Docker
          command: docker build -t my-node-app:latest .
      - run:
          name: Se connecter à Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          environment:
            DOCKER_USERNAME: $DOCKER_USERNAME
            DOCKER_PASSWORD: $DOCKER_PASSWORD
      - run:
          name: Pousser l'image Docker
          command: docker push my-node-app:latest

  kubernetes-deploy:
    docker:
      - image: circleci/kubernetes:1.21.0
    steps:
      - checkout
      - run:
          name: Configurer Kubernetes
          command: |
            mkdir -p ~/.kube
            echo "$KUBECONFIG" > ~/.kube/config
      - run:
          name: Appliquer la configuration
          command: kubectl apply -f deployment.yaml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - docker-build:
          requires:
            - build
      - kubernetes-deploy:
          requires:
            - docker-build