version: 2.1
orbs:
  node: circleci/node@5.1.0
  kubernetes: circleci/kubernetes@2.0.0
jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: apt-get update && apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t dancegep/my-k8s-app:latest .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push dancegep/my-k8s-app:latest
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install_kubectl
 #     - kubernetes/install_kubeconfig:
 #         kubeconfig: KUBECONFIG_DATA
      - run:
          name: test
          command: |
            kubectl config view --minify
      - kubernetes/create_or_update_resource:
          get_rollout_status: true
          resource_file_path: ./k8/deployment.yaml
          resource_name: deployment/my-k8s-deployment
          show_kubectl_command: true
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl set image deployment/my-k8s-deployment my-k8s-app=dancegep/my-k8s-app:latest
      - run:
          name: Restart pods
          command: |
            kubectl rollout restart deployment my-k8s-deployment

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: circleci-agent