version: 2.1
orbs:
  node: circleci/node@5.1.0
  kubernetes: circleci/kubernetes@2.0.0
jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: apt-get update && apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t dancegep/my-k8s-app:latest .
      - run:
          name: test
          command: echo $CIRCLE_SHA1
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push dancegep/my-k8s-app:latest
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install_kubectl
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl set image deployment/my-k8s-deployment my-k8s-app=dancegep/my-k8s-app:latest -n <<parameters.namespace>>
      - run:
          name: Restart pods
          command: |
            kubectl rollout restart deployment my-k8s-deployment -n <<parameters.namespace>>

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build